__PIPELINE_INFO__:
    name: 'Example Pipeline'
    version: '0.00.1'
    author: 'mnursey'
    data_type:
    input_type:
    output_type:
    host_cluster:
    date_created: '2019-05-07'
    date_last_updated:
    Kronos_version: '2.3.0'
__GENERAL__:
    docker: '__REQUIRED__'
__SHARED__:
    img_loc :
    patch_loc:
    anno_loc:
__SAMPLES__:

TASK_A:
    reserved:
        component_name: 'kronos_component_singularity'
        component_version: '0.00.1'
        seed_version: '0.00.1'
    run:
        use_cluster: False
        memory: '128G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars:
        boilerplate:
        merge: True
        requirements:
            docker:
        parallel_run: False
        parallel_params: []
        interval_file:
    component:
        input_files:
            config_file_location: "/projects/ovcare/classification/cchen/ml/pipeline/train_ec_tumornormal_1.json"
            linker_location: "/projects/ovcare/classification/cchen/ml"
            singularity_image: "/home/cochen/cchen/ml/docker_benchmark_pytorch/benchmark_pytorch_latest.sif"
            slurm_job_name: "train_ec_tumornormal_sing"
            slurm_num_cpu: 2
            slurm_output: "/home/cochen/cchen/ml/slurm/train_ec_tumornormal_sing.%j.out"
            slurm_error: "/home/cochen/cchen/ml/slurm/train_ec_tumornormal_sing.%j.err"
            slurm_machine: "dlhost02"
            slurm_queue: "dgxV100"
            slurm_num_gpu: 2
            slurm_max_time: "90:00:00"
            singularity_args: "--nv"
            slurm_memory: "100G"
        output_files:
        parameters:

TASK_B:
    reserved:
        component_name: 'kronos_component_singularity'
        component_version: '0.00.1'
        seed_version: '0.00.1'
    run:
        use_cluster: False
        memory: '128G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars:
        boilerplate:
        merge: True
        requirements:
            docker:
        parallel_run: False
        parallel_params: []
        interval_file:
    component:
        input_files:
            config_file_location: "/projects/ovcare/classification/cchen/ml/pipeline/train_ec_tumornormal_2.json"
            linker_location: "/projects/ovcare/classification/cchen/ml"
            singularity_image: "/home/cochen/cchen/ml/docker_benchmark_pytorch/benchmark_pytorch_latest.sif"
            slurm_job_name: "train_ec_tumornormal_sing"
            slurm_num_cpu: 2
            slurm_output: "/home/cochen/cchen/ml/slurm/train_ec_tumornormal_sing.%j.out"
            slurm_error: "/home/cochen/cchen/ml/slurm/train_ec_tumornormal_sing.%j.err"
            slurm_machine: "dlhost02"
            slurm_queue: "dgxV100"
            slurm_num_gpu: 2
            slurm_max_time: "90:00:00"
            singularity_args: "--nv"
            slurm_memory: "100G"
        output_files:
        parameters:

TASK_C:
    reserved:
        component_name: 'kronos_component_singularity'
        component_version: '0.00.1'
        seed_version: '0.00.1'
    run:
        use_cluster: False
        memory: '128G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars:
        boilerplate:
        merge: True
        requirements:
            docker:
        parallel_run: False
        parallel_params: []
        interval_file:
    component:
        input_files:
            config_file_location: "/projects/ovcare/classification/cchen/ml/pipeline/train_ec_tumornormal_3.json"
            linker_location: "/projects/ovcare/classification/cchen/ml"
            singularity_image: "/home/cochen/cchen/ml/docker_benchmark_pytorch/benchmark_pytorch_latest.sif"
            slurm_job_name: "train_ec_tumornormal_sing"
            slurm_num_cpu: 2
            slurm_output: "/home/cochen/cchen/ml/slurm/train_ec_tumornormal_sing.%j.out"
            slurm_error: "/home/cochen/cchen/ml/slurm/train_ec_tumornormal_sing.%j.err"
            slurm_machine: "dlhost02"
            slurm_queue: "dgxV100"
            slurm_num_gpu: 2
            slurm_max_time: "90:00:00"
            singularity_args: "--nv"
            slurm_memory: "100G"
        output_files:
        parameters: